# Generated by Django 3.1.7 on 2021-04-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
    ]
